### PR TITLE
Improved design and Firefox support.

### PR DESCRIPTION
**Pull request by neauoire**
Improved design, improved Firefox support(fixed toolbar issues with input[number]).

### CODE REVIEW

**Comment by neauoire** [comment]
## Before

screen shot 2018-09-16 at 9 40 50 am

## After

screen shot 2018-09-16 at 9 41 09 am

**Comment by baku89** [comment]
Thank you a lot for your UI improvement and bug fixes for FireFox...!
You UI looks much more coherent in terms of rounded border and simplified color scheme.

Recently I don't have enough time to work on this, yet I will make sure to continue this project.

**Comment by neauoire** [comment]
I will do a bit more change over the next few weeks.
I use Pentool for work, it's excellent. Thank you for building it.

**Comment by baku89** [comment]
You're welcome. It was a first time for me to receive PR except for 'fix typo' haha
While I have to do paid works for the time being, I'm looking forward to your further suggestion!

**Pull request merged**
